language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - cd app_60
  - gem install bundler --pre
script: 'bundle exec rake && bundle exec guard-jasmine --server-timeout=60'
branches:
  only:
    - master
    - backend
    - frontend
notifications:
  email:
    - felix@felixsoum.com
    - un.tremblay@gmailcom
    - ldohxc@hotmail.com
